version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    depends_on:
      - db
    env_file:
      - ../.env

  db:
    image: sqlite:latest
    volumes:
      - sqlite_data:/data
    environment:
      - SQLITE_DATABASE=streaming_db

volumes:
  sqlite_data: