# Generated by Django 4.2.25 on 2025-10-07 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("file_url", models.URLField(verbose_name="URL do Arquivo")),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL da Miniatura"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("audio", "Áudio"), ("video", "Vídeo")],
                        max_length=10,
                        verbose_name="Tipo de Conteúdo",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="Duração"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do Arquivo (bytes)"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Público"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("published", "Publicado"),
                            ("archived", "Arquivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizações"
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="Curtidas"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo",
                "verbose_name_plural": "Conteúdos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_public"],
                        name="content_con_status_9375ff_idx",
                    ),
                    models.Index(
                        fields=["content_type"], name="content_con_content_5aa5f4_idx"
                    ),
                    models.Index(
                        fields=["creator"], name="content_con_creator_f0227d_idx"
                    ),
                ],
            },
        ),
    ]
